version: "3"

services: 
    web:
        container_name: webapp
        restart: always
        build: .
        ports: 
            - "5000:3000"
        links: 
            - mongodb
        volumes: 
            - .:/usr/src/app
    mongodb:
        container_name: database
        image: mongo
        ports: 
            - "27018:27017"
        logging:
            driver: none
